# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: takler/server/protocol/takler.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#takler/server/protocol/takler.proto\x12\x0ftakler_protocol\"0\n\x0fServiceResponse\x12\x0c\n\x04\x66lag\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"(\n\x13\x43hildCommandOptions\x12\x11\n\tnode_path\x18\x01 \x01(\t\"[\n\x0bInitCommand\x12;\n\rchild_options\x18\x01 \x01(\x0b\x32$.takler_protocol.ChildCommandOptions\x12\x0f\n\x07task_id\x18\x02 \x01(\t\"N\n\x0f\x43ompleteCommand\x12;\n\rchild_options\x18\x01 \x01(\x0b\x32$.takler_protocol.ChildCommandOptions\"[\n\x0c\x41\x62ortCommand\x12;\n\rchild_options\x18\x01 \x01(\x0b\x32$.takler_protocol.ChildCommandOptions\x12\x0e\n\x06reason\x18\x02 \x01(\t\"_\n\x0c\x45ventCommand\x12;\n\rchild_options\x18\x01 \x01(\x0b\x32$.takler_protocol.ChildCommandOptions\x12\x12\n\nevent_name\x18\x02 \x01(\t\"#\n\x0eRequeueCommand\x12\x11\n\tnode_path\x18\x01 \x01(\t\"\r\n\x0bShowRequest\"\x1e\n\x0cShowResponse\x12\x0e\n\x06output\x18\x01 \x01(\t2\x95\x04\n\x0cTaklerServer\x12R\n\x0eRunInitCommand\x12\x1c.takler_protocol.InitCommand\x1a .takler_protocol.ServiceResponse\"\x00\x12Z\n\x12RunCompleteCommand\x12 .takler_protocol.CompleteCommand\x1a .takler_protocol.ServiceResponse\"\x00\x12T\n\x0fRunAbortCommand\x12\x1d.takler_protocol.AbortCommand\x1a .takler_protocol.ServiceResponse\"\x00\x12T\n\x0fRunEventCommand\x12\x1d.takler_protocol.EventCommand\x1a .takler_protocol.ServiceResponse\"\x00\x12X\n\x11RunRequeueCommand\x12\x1f.takler_protocol.RequeueCommand\x1a .takler_protocol.ServiceResponse\"\x00\x12O\n\x0eRunShowRequest\x12\x1c.takler_protocol.ShowRequest\x1a\x1d.takler_protocol.ShowResponse\"\x00\x62\x06proto3')



_SERVICERESPONSE = DESCRIPTOR.message_types_by_name['ServiceResponse']
_CHILDCOMMANDOPTIONS = DESCRIPTOR.message_types_by_name['ChildCommandOptions']
_INITCOMMAND = DESCRIPTOR.message_types_by_name['InitCommand']
_COMPLETECOMMAND = DESCRIPTOR.message_types_by_name['CompleteCommand']
_ABORTCOMMAND = DESCRIPTOR.message_types_by_name['AbortCommand']
_EVENTCOMMAND = DESCRIPTOR.message_types_by_name['EventCommand']
_REQUEUECOMMAND = DESCRIPTOR.message_types_by_name['RequeueCommand']
_SHOWREQUEST = DESCRIPTOR.message_types_by_name['ShowRequest']
_SHOWRESPONSE = DESCRIPTOR.message_types_by_name['ShowResponse']
ServiceResponse = _reflection.GeneratedProtocolMessageType('ServiceResponse', (_message.Message,), {
  'DESCRIPTOR' : _SERVICERESPONSE,
  '__module__' : 'takler.server.protocol.takler_pb2'
  # @@protoc_insertion_point(class_scope:takler_protocol.ServiceResponse)
  })
_sym_db.RegisterMessage(ServiceResponse)

ChildCommandOptions = _reflection.GeneratedProtocolMessageType('ChildCommandOptions', (_message.Message,), {
  'DESCRIPTOR' : _CHILDCOMMANDOPTIONS,
  '__module__' : 'takler.server.protocol.takler_pb2'
  # @@protoc_insertion_point(class_scope:takler_protocol.ChildCommandOptions)
  })
_sym_db.RegisterMessage(ChildCommandOptions)

InitCommand = _reflection.GeneratedProtocolMessageType('InitCommand', (_message.Message,), {
  'DESCRIPTOR' : _INITCOMMAND,
  '__module__' : 'takler.server.protocol.takler_pb2'
  # @@protoc_insertion_point(class_scope:takler_protocol.InitCommand)
  })
_sym_db.RegisterMessage(InitCommand)

CompleteCommand = _reflection.GeneratedProtocolMessageType('CompleteCommand', (_message.Message,), {
  'DESCRIPTOR' : _COMPLETECOMMAND,
  '__module__' : 'takler.server.protocol.takler_pb2'
  # @@protoc_insertion_point(class_scope:takler_protocol.CompleteCommand)
  })
_sym_db.RegisterMessage(CompleteCommand)

AbortCommand = _reflection.GeneratedProtocolMessageType('AbortCommand', (_message.Message,), {
  'DESCRIPTOR' : _ABORTCOMMAND,
  '__module__' : 'takler.server.protocol.takler_pb2'
  # @@protoc_insertion_point(class_scope:takler_protocol.AbortCommand)
  })
_sym_db.RegisterMessage(AbortCommand)

EventCommand = _reflection.GeneratedProtocolMessageType('EventCommand', (_message.Message,), {
  'DESCRIPTOR' : _EVENTCOMMAND,
  '__module__' : 'takler.server.protocol.takler_pb2'
  # @@protoc_insertion_point(class_scope:takler_protocol.EventCommand)
  })
_sym_db.RegisterMessage(EventCommand)

RequeueCommand = _reflection.GeneratedProtocolMessageType('RequeueCommand', (_message.Message,), {
  'DESCRIPTOR' : _REQUEUECOMMAND,
  '__module__' : 'takler.server.protocol.takler_pb2'
  # @@protoc_insertion_point(class_scope:takler_protocol.RequeueCommand)
  })
_sym_db.RegisterMessage(RequeueCommand)

ShowRequest = _reflection.GeneratedProtocolMessageType('ShowRequest', (_message.Message,), {
  'DESCRIPTOR' : _SHOWREQUEST,
  '__module__' : 'takler.server.protocol.takler_pb2'
  # @@protoc_insertion_point(class_scope:takler_protocol.ShowRequest)
  })
_sym_db.RegisterMessage(ShowRequest)

ShowResponse = _reflection.GeneratedProtocolMessageType('ShowResponse', (_message.Message,), {
  'DESCRIPTOR' : _SHOWRESPONSE,
  '__module__' : 'takler.server.protocol.takler_pb2'
  # @@protoc_insertion_point(class_scope:takler_protocol.ShowResponse)
  })
_sym_db.RegisterMessage(ShowResponse)

_TAKLERSERVER = DESCRIPTOR.services_by_name['TaklerServer']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SERVICERESPONSE._serialized_start=56
  _SERVICERESPONSE._serialized_end=104
  _CHILDCOMMANDOPTIONS._serialized_start=106
  _CHILDCOMMANDOPTIONS._serialized_end=146
  _INITCOMMAND._serialized_start=148
  _INITCOMMAND._serialized_end=239
  _COMPLETECOMMAND._serialized_start=241
  _COMPLETECOMMAND._serialized_end=319
  _ABORTCOMMAND._serialized_start=321
  _ABORTCOMMAND._serialized_end=412
  _EVENTCOMMAND._serialized_start=414
  _EVENTCOMMAND._serialized_end=509
  _REQUEUECOMMAND._serialized_start=511
  _REQUEUECOMMAND._serialized_end=546
  _SHOWREQUEST._serialized_start=548
  _SHOWREQUEST._serialized_end=561
  _SHOWRESPONSE._serialized_start=563
  _SHOWRESPONSE._serialized_end=593
  _TAKLERSERVER._serialized_start=596
  _TAKLERSERVER._serialized_end=1129
# @@protoc_insertion_point(module_scope)
